//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryBox.Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerInfo
    {
        public System.Guid CareerId { get; set; }
        public string AboutMe { get; set; }
        public string Facebook { get; set; }
        public string LinkedIn { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Skype { get; set; }
    
        public virtual Career Career { get; set; }
    }
}
