//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryBox.Main.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jewelryBoxContext : DbContext
    {
        public jewelryBoxContext()
            : base("name=jewelryBoxContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CareerInfo> CareerInfoes { get; set; }
        public virtual DbSet<Career> Careers { get; set; }
        public virtual DbSet<Timeline> Timelines { get; set; }
        public virtual DbSet<VisitorMessage> VisitorMessages { get; set; }
        public virtual DbSet<WorkDetail> WorkDetails { get; set; }
    }
}
