//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryBox.Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorMessage
    {
        public int Id { get; set; }
        public System.Guid CareerId { get; set; }
        public string SenderName { get; set; }
        public string SenderEmailAddress { get; set; }
        public string Message { get; set; }
    
        public virtual Career Career { get; set; }
    }
}
